#spring:
#  jpa:
#    hibernate:
#      use-new-id-generator-mappings: false
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  port: 8080
storage:
  filepath: "./whitelist.txt"